import { chromium } from '@playwright/test';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=process.env.SEARCHPROOF_TEST_URL||'http://127.0.0.1:5173';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);
await page.getByRole('button',{name:'새 모의 수색',exact:true}).waitFor({timeout:30000});
await page.getByRole('button',{name:'새 모의 수색',exact:true}).click();
const missionName='브라우저 검사 '+new Date().toISOString();
await page.getByLabel('임무 이름',{exact:true}).fill(missionName);
await page.getByRole('button',{name:'시나리오 계산 및 시작',exact:true}).click();
await page.getByRole('heading',{name:missionName,exact:true}).waitFor({timeout:30000});
await page.waitForTimeout(1800);
fs.mkdirSync('../artifacts',{recursive:true});
await page.screenshot({path:'../artifacts/workspace-desktop.png',fullPage:true});
console.log(JSON.stringify({errors,title:await page.title(),horizontalOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),canvas:await page.locator('.maplibregl-canvas').count()}));
for(const layer of ['거리','지형','행동','비교','종합']){
  await page.locator('.layer-tabs').getByRole('button',{name:layer,exact:true}).click();
  await page.waitForTimeout(200);
}
await page.locator('.zone-card').first().click();
await page.getByRole('button',{name:'수색 후보 승인',exact:true}).click();
await page.getByRole('button',{name:'후보 승인됨',exact:true}).waitFor();
await page.getByRole('button',{name:'구역 상세 닫기',exact:true}).click();
await page.getByRole('button',{name:'수색 기록',exact:true}).first().click();
await page.getByRole('button',{name:'합성 훈련 트랙으로 체험'}).click();
await page.getByText('결과 확정 대기',{exact:true}).waitFor({timeout:20000});
await page.getByRole('button',{name:'미발견 확정',exact:true}).first().click();
await page.locator('dialog').getByRole('button',{name:'미발견 확정',exact:true}).click();
await page.getByText('미발견 반영 완료',{exact:true}).waitFor({timeout:20000});
await page.locator('.layer-tabs').getByRole('button',{name:'종합',exact:true}).click();
await page.waitForTimeout(1000);
await page.screenshot({path:'../artifacts/workspace-after-search.png',fullPage:true});
await page.getByRole('button',{name:'근거 장부',exact:true}).first().click();
await page.getByLabel('관찰 내용').fill('모의 수색 표식 확인. 실제 사건 제보 아님.');
await page.getByRole('button',{name:'근거 기록',exact:true}).click();
await page.getByText('모의 수색 표식 확인. 실제 사건 제보 아님.',{exact:true}).waitFor();
await page.getByRole('button',{name:'인계 패키지',exact:true}).click();
const download=page.waitForEvent('download');
await page.getByRole('link',{name:'ZIP',exact:true}).click();
await (await download).saveAs('../artifacts/searchproof-demo-package.zip');
await page.locator('input[accept=".zip"]').setInputFiles('../artifacts/searchproof-demo-package.zip');
await page.getByText(/개 파일의 해시가 일치합니다/).waitFor();
const popup=page.waitForEvent('popup');
await page.locator('dialog').getByRole('button',{name:'열기',exact:true}).click();
const report=await popup;await report.waitForLoadState();
assert.ok((await report.textContent('body')).includes(missionName));
await report.close();
await page.getByRole('button',{name:'닫기',exact:true}).click();
await page.getByRole('button',{name:'버전 기록',exact:true}).click();
await page.getByRole('button',{name:/v0.*이동 시나리오 계산/}).click();
await page.getByRole('button',{name:'현재 v0',exact:true}).waitFor();
await page.getByRole('button',{name:/v1.*미발견 결과 반영/}).click();
await page.getByRole('button',{name:'현재 v1',exact:true}).waitFor();
await page.getByRole('button',{name:'수색 지도',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(500);
await page.screenshot({path:'../artifacts/workspace-mobile.png',fullPage:true});
console.log(JSON.stringify({workflow:'upload > confirm > ledger > export passed',errors,mobileOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)}));
assert.deepEqual(errors,[]);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await browser.close();
