import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const base=process.env.SEARCHPROOF_TEST_URL||'http://127.0.0.1:8000';
const browser=await chromium.launch();
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:2});
const page=await context.newPage();
const errors=[],mutations=[],tiles=[];
page.on('pageerror',e=>errors.push(e.message));
context.on('request',r=>{if(r.url().includes('/api/')&&r.method()!=='GET')mutations.push(r.url());});
page.on('response',r=>{if(r.url().includes('s2cloudless-2025_3857'))tiles.push({url:r.url(),status:r.status(),type:r.headers()['content-type']});});
fs.mkdirSync('../artifacts',{recursive:true});
try {
  const missions=await (await context.request.get(base+'/api/missions')).json();
  const path=base+'/api/missions/'+missions[0].id;
  const before=await (await context.request.get(path)).json();
  await page.goto(base);
  await page.getByTestId('basemap-status').filter({hasText:/고해상도 벡터|오프라인 분석 지도/}).waitFor({timeout:45000});
  assert.equal(tiles.length,0,'satellite imagery must load only on request');
  const canvas=await page.locator('canvas').elementHandle();
  await page.getByRole('button',{name:'위성사진',exact:true}).click();
  await page.getByTestId('basemap-status').filter({hasText:'위성사진 (Sentinel-2)'}).waitFor({timeout:25000});
  await page.waitForFunction(()=>document.querySelector('.satellite-credit')?.textContent.includes('Copernicus'));
  await page.waitForTimeout(1500);
  assert.ok(tiles.some(t=>t.status===200&&t.type?.includes('image/jpeg')),JSON.stringify(tiles));
  assert.ok(tiles.every(t=>Number(t.url.split('/').at(-3))<=14),'do not over-request native resolution');
  assert.ok(await canvas.evaluate(c=>c===document.querySelector('canvas')),'switch must preserve the map instance');
  await page.screenshot({path:'../artifacts/satellite-desktop.png'});
  await page.getByLabel('도로와 지명',{exact:true}).uncheck();
  await page.getByRole('button',{name:'지도만 보기',exact:true}).click();
  await page.waitForTimeout(300);
  await page.screenshot({path:'../artifacts/satellite-imagery-only.png'});
  await page.getByRole('button',{name:'수색 레이어 켜기',exact:true}).click();
  await page.getByLabel('도로와 지명',{exact:true}).check();
  await page.getByRole('button',{name:'일반 지도',exact:true}).click();
  assert.equal(await page.locator('.satellite-notice').count(),0);
  await page.getByRole('button',{name:'위성사진',exact:true}).click();
  await page.getByTestId('basemap-status').filter({hasText:'위성사진 (Sentinel-2)'}).waitFor();
  await page.getByRole('button',{name:'골목과 건물까지 확대',exact:true}).click();
  await page.waitForTimeout(1200);
  assert.ok(tiles.every(t=>Number(t.url.split('/').at(-3))<=14));
  await page.locator('.map-home').click();
  await page.waitForTimeout(700);
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(500);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const credit=await page.locator('.attribution').boundingBox();
  for(const selector of ['.compare-switch','.maplibregl-ctrl-scale','.maplibregl-ctrl-zoom-out']) {
    const control=await page.locator(selector).boundingBox();
    assert.ok(control.y+control.height<=credit.y,selector+' must not overlap credits');
  }
  await page.screenshot({path:'../artifacts/satellite-mobile.png',fullPage:true});

  const failure=await context.newPage();
  failure.on('pageerror',e=>errors.push(e.message));
  await failure.route('https://tiles.maps.eox.at/**',route=>route.abort());
  await failure.goto(base);
  await failure.getByTestId('basemap-status').filter({hasText:/고해상도 벡터|오프라인 분석 지도/}).waitFor({timeout:45000});
  await failure.getByRole('button',{name:'위성사진',exact:true}).click();
  await failure.getByText(/위성사진 연결에 실패해/).waitFor({timeout:20000});
  await failure.screenshot({path:'../artifacts/satellite-fallback.png'});
  await failure.unroute('https://tiles.maps.eox.at/**');
  await failure.getByRole('button',{name:'다시 시도',exact:true}).click();
  await failure.getByTestId('basemap-status').filter({hasText:'위성사진 (Sentinel-2)'}).waitFor({timeout:25000});
  const stalled=await context.newPage();
  stalled.on('pageerror',e=>errors.push(e.message));
  await stalled.route('https://tiles.maps.eox.at/**',()=>{});
  await stalled.goto(base);
  await stalled.getByTestId('basemap-status').filter({hasText:/고해상도 벡터|오프라인 분석 지도/}).waitFor({timeout:45000});
  await stalled.getByRole('button',{name:'위성사진',exact:true}).click();
  await stalled.getByText(/위성사진 연결에 실패해/).waitFor({timeout:20000});
  await stalled.close();
  const after=await (await context.request.get(path)).json();
  assert.equal(before.receipt.hash,after.receipt.hash);
  assert.equal(before.version,after.version);
  assert.deepEqual(mutations,[]);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,imageryResponses:tiles.length,successfulImages:tiles.filter(t=>t.status===200).length,mutations:0,receiptUnchanged:true,fallbackAndRetry:true,timeoutFallback:true,mobile:true}));
} finally {await browser.close();}
