// Disposable-database browser check; never trains or modifies real mission data.
import {chromium,request} from '@playwright/test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
const root=path.resolve('..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'cheonrajimang-walk-test-'));
const socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));
const port=socket.address().port;await new Promise(r=>socket.close(r));
const base='http://127.0.0.1:'+port;
const server=spawn(path.join(root,'.venv/bin/python'),['-m','uvicorn','backend.main:app','--host','127.0.0.1','--port',String(port)],{cwd:root,env:{...process.env,SEARCHPROOF_DB:path.join(temp,'test.sqlite3')},stdio:'ignore'});
let browser,api;
try{
  api=await request.newContext({baseURL:base});
  for(let i=0;i<60;i++){try{if((await api.get('/api/health')).ok())break;}catch{}await new Promise(r=>setTimeout(r,250));}
  const mid=(await (await api.get('/api/missions')).json())[0].id;
  const before=await (await api.get('/api/missions/'+mid)).json();
  browser=await chromium.launch();
  const page=await browser.newPage({viewport:{width:1440,height:1200},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/?view=walking-lab');
  await page.getByTestId('walking-results').waitFor();
  await page.getByText('72.6%',{exact:true}).waitFor();
  assert.match(await page.getByTestId('walking-horizon-evaluation').innerText(),/214개/);
  assert.match(await page.getByTestId('walking-status').innerText(),/미충족/);
  assert.match(await page.locator('.walk-metrics').innerText(),/53,254/);
  const first=await (await api.get('/api/ai/walking/status')).json();
  const wait=page.waitForResponse(r=>r.url().includes('/walking/simulate?seconds=300'));
  await page.getByLabel('보행 실험 시간').fill('300');
  const at300=await (await wait).json();
  assert.equal(at300.seconds,300);assert.equal(at300.mass,1);
  await page.getByTestId('walking-results').waitFor();
  assert.match(await page.getByTestId('walking-results').innerText(),/300초/);
  await page.screenshot({path:'../artifacts/geolife-walking-desktop.png'});
  const next=page.waitForResponse(r=>r.url().includes('/walking/simulate?seconds=300&seed=43'));
  await page.getByRole('button',{name:'다른 가상 경로 생성'}).click();
  const newSeed=await (await next).json();assert.notDeepEqual(newSeed.cells,at300.cells);
  await page.getByTestId('walking-results').waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'../artifacts/geolife-walking-mobile.png'});
  await page.locator('.walk-chart').scrollIntoViewIfNeeded();
  await page.screenshot({path:'../artifacts/geolife-walking-mobile-chart.png'});
  await page.getByTestId('walking-horizon-evaluation').scrollIntoViewIfNeeded();
  await page.screenshot({path:'../artifacts/geolife-horizon-mobile.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.goto(base);
  await page.getByRole('link',{name:'보행 학습 결과 ↗'}).waitFor();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.getByRole('link',{name:'보행 학습 결과 ↗'}).click();
  await page.getByTestId('walking-results').waitFor();
  const after=await (await api.get('/api/missions/'+mid)).json();
  assert.equal(after.receipt.hash,before.receipt.hash);
  assert.equal(after.versions.length,before.versions.length);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({ok:true,model_id:first.model_id,checks:['trained status','time change','seed change','mass conservation','desktop/mobile','horizon coverage and uncertainty','main entry link','mission unchanged'],screenshots:4}));
}finally{await browser?.close();await api?.dispose();server.kill('SIGTERM');}
